import type { Metadata } from "next";
import { ThemeProvider } from '@/components/ui/theme-provider';
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ru" suppressHydrationWarning>
            <body>
                <ThemeProvider>
                    <main className="px-4 min-h-screen flex flex-col items-center">
                        {children}
                    </main>
                </ThemeProvider>
                <Toaster />
            </body>
        </html>
    )
}